### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by jvinkovic** [reinhard-brandstaedter/solarflow-statuspage#40]
![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/5563016/f4f981fc-4ac1-4305-a5f1-d982149a9f98)

**Comment by z-master42** [comment]
A little more information would be nice. Are the environment variables set correctly?

**Comment by jvinkovic** [comment]
Yes. They are correct.

**Comment by z-master42** [comment]
What else is in the log?

**Comment by jvinkovic** [comment]
Nothing

**Comment by z-master42** [comment]
Ok, that's not really helpful.

**Comment by dabenzel** [comment]
Same Issue here.
Changed my SolarFlow to "Germany" as Region
These env-Configs do not work:
```
ZEN_MQTT = mqtt.zen-iot.com
ZEN_API = https://app.zendure.tech
```
or
```
ZEN_MQTT = mqtt.zen-iot.com
ZEN_API = https://app.zendure.tech/eu
```
or
```
ZEN_MQTT = mqtteu.zen-iot.com
ZEN_API = https://app.zendure.tech
```


Logs:
```solarflow-statuspage  | 2024-02-04 12:02:18,715:ERROR: No configuration file (config.ini) found in execution directory! Using environment variables.
solarflow-statuspage  | 2024-02-04 12:02:18,767:INFO: Authenticating with Zendure ...
solarflow-statuspage  | 2024-02-04 12:02:20,341:INFO: Getting device list ...
solarflow-statuspage  | 2024-02-04 12:02:20,888:INFO: []
solarflow-statuspage  | 2024-02-04 12:02:20,889:ERROR: Connecting to Zendure's MQTT broker failed!
solarflow-statuspage  | Traceback (most recent call last):
solarflow-statuspage  |   File "//solarflow-status.py", line 295, in zendure_mqtt_background_task
solarflow-statuspage  |     auth = get_auth()
solarflow-statuspage  |   File "//solarflow-status.py", line 288, in get_auth
solarflow-statuspage  |     log.info(f'Zendure Auth: {auth}')
solarflow-statuspage  | NameError: name 'auth' is not defined`

**Comment by z-master42** [comment]
Have you re-registered your SolarFlow on the EU server using the curl command?

**Comment by dabenzel** [comment]
Hi!
Yes, I think:
```curl -i -v --json "{'snNumber': 'XXXX', 'account': 'XXXX'}" https://app.zendure.tech/eu/developer/api/apply
<__Removed__>
<
{"code":200,"success":true,"data":{"appKey":"XXXX","secret":"XXXX","mqttUrl":"mqtt.zen-iot.com","port":1883},"msg":"Successful operation"}* Connection #0 to host app.zendure.tech left intact```

**Comment by z-master42** [comment]
Does it work if you use the two URLs? The one from your curl command and the one from the answer?

**Comment by dabenzel** [comment]
You mean like this:
````
ZEN_MQTT = mqtt.zen-iot.com
ZEN_API = https://app.zendure.tech/eu/developer/api/apply
```
Nope. Other ways, I showed at my first comment.

How do you use it with EU-Server?

**Comment by z-master42** [comment]
I didn't switch because I didn't want to lose the statistics in the app.

I have now played around with ZEN_MQTT and ZEN_API. I can specify whatever I want. The EU server, the global server or just a jumble of letters. It always works. Apparently it always falls back to the fallback, which is the global server.

Have you tried changing that directly in the config.ini and loading it into the container?

**Comment by dabenzel** [comment]
Okay, I switched to global server and it works again.
I'm not good in Python, but I think, it tries to append "v2" to both API-URLS, but the EU Url does'nt have "v2".
Reference Line 21 and Line 28:
https://github.com/reinhard-brandstaedter/solarflow-statuspage/blob/740bace043e309f8d7a9e0007c86aecefb38890b/src/zenapi/ZendureAPI.py#L20-L28

But Global and Europe URL are the following:
Global: `https://app.zendure.tech/v2/developer/api/apply`
Europe: `https://app.zendure.tech/eu/developer/api/apply`

**Comment by jvinkovic** [comment]
Looks like easiest would be just to use complete url in config and clean up the script.

**Comment by tuxianerDE** [comment]
@jvinkovic  you wanna create a pull request for that change suggestion? Happy to take this into consideration, for the next merge given that Zendure is handling URLs so badly.

**Comment by z-master42** [comment]
I have a new hub and wanted to use it today with the status page, but now I get the same error as in this issue here. I haven't changed anything on my container or in the app.

Log:
```
2024-04-19 16:59:29,265:ERROR: No configuration file (config.ini) found in execution directory! Using environment variables.
2024-04-19 16:59:29,479:INFO: Authenticating with Zendure ...
2024-04-19 16:59:29,489:DEBUG: Starting new HTTPS connection (1): app.zendure.tech:443
2024-04-19 16:59:31,106:DEBUG: https://app.zendure.tech:443 "POST /v2/auth/app/token HTTP/1.1" 200 None
2024-04-19 16:59:31,108:INFO: Getting device list ...
2024-04-19 16:59:31,794:DEBUG: https://app.zendure.tech:443 "POST /v2/productModule/device/queryDeviceListByConsumerId HTTP/1.1" 200 None
2024-04-19 16:59:31,798:INFO: []
2024-04-19 16:59:31,812:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "//solarflow-status.py", line 295, in zendure_mqtt_background_task
    auth = get_auth()
  File "//solarflow-status.py", line 288, in get_auth
    log.info(f'Zendure Auth: {auth}')

NameError: name 'auth' is not defined
```

**Comment by z-master42** [comment]
Update: Found the error. New hub means new device sharing for the second account. Oh boy.

**Comment by joe63** [comment]
I can also not connect:


docker run --rm --env-file .env -p 127.0.0.1:5000:5000 --name solarflow-statuspage rbrandstaedter/solarflow-statuspage:master --online
2024-06-07 06:47:28,357:ERROR: No configuration file (config.ini) found in execution directory! Using environment variables.
2024-06-07 06:47:28,392:INFO: Authenticating with Zendure ...
2024-06-07 06:47:31,634:INFO: Getting device list ...
2024-06-07 06:47:32,793:INFO: []
2024-06-07 06:47:32,795:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "//solarflow-status.py", line 295, in zendure_mqtt_background_task
    auth = get_auth()
  File "//solarflow-status.py", line 288, in get_auth
    log.info(f'Zendure Auth: {auth}')
NameError: name 'auth' is not defined




curl -i -v --json "{'snNumber': 'H**********', 'account': 'j*******@gmx.at'}" https://app.zendure.tech/eu/developer/api/apply

{"code":200,"success":true,"data":{"appKey":"2****","secret":"8***********","mqttUrl":"mqtt.zen-iot.com","port":1883},"msg":"Successful operation"}* Connection #0 to host app.zendure.tech left intact


my .env-file

ZEN_USER=z*******
ZEN_PASSWD=Z****
MQTT_HOST=mqtt.zen-iot.com
MQTT_PORT=1883
MQTT_USER=2****
MQTT_PWD=8***********
PROD_NAME=SolarFlow Hub 2000

can you pls give me a hint?

**Comment by joe63** [comment]
Aha,

where (in the Dockerfile)  an how (what I have to change)?

**Comment by joe63** [comment]
I have tried it several times with different options ( eu vs global, englisch/ deutsch = Austria/Österreich , different Email-adresses) because of I didn’t receive a verification-code.

 

Only as I created a new email-account ( ***@***.*** ***@***.***>   [ joe_fuchs.gmx.at and ***@***.*** ***@***.***>  seem not to work because of then missing point] ) I got the verification-code by mail.

 

So I cannot say if I at least used eu or global.

 

Is there a possibilty to check this afterwards?

 

PS

Die Kommunikation auf Deutsch wäre mir lieber! 

 

 

 

Von: z-master42 ***@***.***> 
Gesendet: Freitag, 7. Juni 2024 11:39
An: reinhard-brandstaedter/solarflow-statuspage ***@***.***>
Cc: joe63 ***@***.***>; Comment ***@***.***>
Betreff: Re: [reinhard-brandstaedter/solarflow-statuspage] Cannot connect (Issue #40)

 

Which server (region) are you on in the Zendure app?

**Comment by z-master42** [comment]
Wenn ich nichts übersehen habe muss nur in der ZendureAPI.py v2 auf eu geändert werden. Sicherheitshalber ist das in den anderen .py auch noch gegen zu checken.

Wechsel auf global heißt Gerät aus der App löschen, Region in der App ändern, Gerät neu hinzufügen.

Dann über curl Gerät neu am globalen Server (v2) registrieren.

Hinweis: Beim wechsel der Region in der App verbleibt die bisherige Statistik in der App auf dem "alten Server", ist danach also nicht mehr einsehbar.

**Comment by joe63** [comment]
**Danke** der Connect funktioniert jetzt! Ich habe die Region gewechselt!

_@Additionally the statuspage can push the data it reads from Zendure's cloud service to a local MQTT broker_
wie funktioniert das?

**Comment by z-master42** [comment]
Da wo du in deiner env-Datei den Zendure-Broker angegeben hast kommt eigentlich wenn dann dein lokaler Broker rein, wenn du einen hast. Die "Statuspage" stellt die einzelnen Hubwerte dann über das Topic solarflow-hub bereit.

> ZEN_USER=z*******
ZEN_PASSWD=Z****
MQTT_HOST=mqtt.zen-iot.com
MQTT_PORT=1883
MQTT_USER=2****
MQTT_PWD=8***********
PROD_NAME=SolarFlow Hub 2000

**Comment by z-master42** [comment]
Ich sehe gerade, EU-Server geht mittlerweile auch, nur muss dies explizit über ZEN_API mitgeteilt werden. Hat @jvinkovic vor zwei Tagen erst gepulled. Den Stand hatte ich noch nicht.

**Comment by joe63** [comment]
> Ich sehe gerade, EU-Server geht mittlerweile auch, nur muss dies explizit über ZEN_API mitgeteilt werden. Hat @jvinkovic vor zwei Tagen erst gepushed. Den Stand hatte ich noch nicht.
> 
> @mdillmann https://github.com/reinhard-brandstaedter/solarflow-statuspage/blob/master/README.md?plain=1#L39 hier ist ein ` zuviel.

Wenn man diese Änderung um File durchführt, muss man dann den Container lokal erzeugen??

**Comment by joe63** [comment]
> Da wo du in deiner env-Datei den Zendure-Broker angegeben hast kommt eigentlich wenn dann dein lokaler Broker rein, wenn du einen hast. Die "Statuspage" stellt die einzelnen Hubwerte dann über das Topic solarflow-hub bereit.

**Danke,** so ist es sehr gut um es weiterzuverarbeiten.

Ein letztes noch für heute:

![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/6555368/62c8d013-6567-4fdc-95bb-95fa14b94ddc)
 
Welche Werte sollten hier drin stehen?

**Comment by z-master42** [comment]
> > Ich sehe gerade, EU-Server geht mittlerweile auch, nur muss dies explizit über ZEN_API mitgeteilt werden. Hat @jvinkovic vor zwei Tagen erst gepushed. Den Stand hatte ich noch nicht.
> > 
> > @mdillmann https://github.com/reinhard-brandstaedter/solarflow-statuspage/blob/master/README.md?plain=1#L39 hier ist ein ` zuviel.
> 
> Wenn man diese Änderung um File durchführt, muss man dann den Container lokal erzeugen??

Ja, solange es noch nicht im master-Branch ist.

**Comment by z-master42** [comment]
> > Da wo du in deiner env-Datei den Zendure-Broker angegeben hast kommt eigentlich wenn dann dein lokaler Broker rein, wenn du einen hast. Die "Statuspage" stellt die einzelnen Hubwerte dann über das Topic solarflow-hub bereit.
> 
> **Danke,** so ist es sehr gut um es weiterzuverarbeiten.
> 
> Ein letztes noch für heute:
> 
> ![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/6555368/62c8d013-6567-4fdc-95bb-95fa14b94ddc)
>  
> Welche Werte sollten hier drin stehen?

Der aktuelle Verbrauch deines Stromzählers, wenn dieser Wert per MQTT mitgeteilt werden sollte.

**Comment by mdillmann** [comment]
> Ich sehe gerade, EU-Server wird bald auch gehen, nur muss dies explizit über ZEN_API mitgeteilt werden. Hat @jvinkovic vor zwei Tagen erst gepushed. Den Stand hatte ich noch nicht.
> 
> @mdillmann https://github.com/reinhard-brandstaedter/solarflow-statuspage/blob/master/README.md?plain=1#L39 hier ist ein ` zuviel.

Thanks, I created a PR to correct that typo (VS-Code is sometimes over-enthusiastic ...)

**Comment by joe63** [comment]
@Der aktuelle Verbrauch deines Stromzählers, wenn dieser Wert per MQTT mitgeteilt werden sollte.

über diesen Weg?
 _you can already today publish to the topic iot/73bkTV/<your device id>/properties/write and the statuspage will forward it to to the Zendure MQTT to set properties of the hub._

wird das irgendwo näher beschrieben, wie z.B.: diese Property für den Verbrauch heißen muss damit die Werte dann in diesem Feld angezeigt werden?

**Comment by z-master42** [comment]
> @der aktuelle Verbrauch deines Stromzählers, wenn dieser Wert per MQTT mitgeteilt werden sollte.
> 
> über diesen Weg? _you can already today publish to the topic iot/73bkTV//properties/write and the statuspage will forward it to to the Zendure MQTT to set properties of the hub._
> 
> wird das irgendwo näher beschrieben, wie z.B.: diese Property für den Verbrauch heißen muss damit die Werte dann in diesem Feld angezeigt werden?

Nein, damit kannst du den SolarFlow Hub regeln.

Um deinen aktuellen Bezug in Watt in der Statuspage anzuzeigen musst du diese als reinen Zahlenwert unter dem Topic `solarflow-hub/control/homeUsage` veröffentlichen.

**Comment by joe63** [comment]
danke funktioniert!
![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/6555368/6dcaec56-ee4e-4540-b7a6-3c98870b4e6c)

**Comment by romestylez** [comment]
Ich habe mal eine Frage. Ich habe mein HUB2000 freigegeben. Wenn ich das Ding aber registrieren will geht das nur mit dem Haupt-Account welchen ich auf meinem Handy nutze. Gebe ich das Gerät für einen anderen Account frei und nehme dort die Freigabe an sehe ich nur folgenden Fehler.

{"code":400,"success":false,"data":{},"msg":"Please bind the device first"}

**Comment by romestylez** [comment]
Okay its working now when i use the jason on the account which is initially connected with the HUB. Its not working with shared devices. This really isnt that nice as i want to use the main account on my phone but when i relogin on my phone and restart the docker container i get a login failed again.

**Comment by reinhard-brandstaedter** [comment]
Everytime you log in to the Zendure API (with your user/email) a new authentication token is generated for their MQTT server (which is where all the data for the App/statuspage is coming from). So you can't use the statuspage and the app in parallel.
The idea is to use the statuspage for offline hubs and/or do the controlling og the hub via sf-control and Homeassistant integration (or any other HA system via the local MQTT).

**Comment by z-master42** [comment]
Use your main account to bind and the secondary account to connect via the status page. Works for me too.

**Comment by mrostock** [comment]
Sorry, but I have the same issue here.
I'm trying to connect in online mode. But I get this error message:

```
2024-07-30 18:58:43,631:INFO: Authenticating with Zendure ...
2024-07-30 18:58:47,750:INFO: Getting device list ...
2024-07-30 18:58:48,050:INFO: {'code': 200, 'success': True, 'data': [], 'msg': 'Vorgang erfolgreich'}
2024-07-30 18:58:48,050:INFO: []
2024-07-30 18:58:48,051:INFO: devices: []
2024-07-30 18:58:48,051:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "/opt/solarflow-statuspage/solarflow-statuspage/src/solarflow-status.py", line 313, in zendure_mqtt_background_task
    auth = get_auth()
           ^^^^^^^^^^
  File "/opt/solarflow-statuspage/solarflow-statuspage/src/solarflow-status.py", line 306, in get_auth
    log.info(f'Zendure Auth: {auth}')
                              ^^^^
NameError: name 'auth' is not defined
```

I added an additional log entry. As you can see I get an empty response when the scripts tries to retrieve the list of devices:
`{'code': 200, 'success': True, 'data': [], 'msg': 'Vorgang erfolgreich'}`

Has anybody a fix for me?

**Comment by z-master42** [comment]
Are you on the global or the EU server?
Something seems to have broken at 0.24. I think this is related #50.

Try 0.19 (if you are on the global server).

**Comment by mrostock** [comment]
Thank you for your answer! But version 0.19 returns the same error. And yes I think I'am on the global server. I didn't change anything to use the eu server.

```
2024-07-31 10:11:30,544:INFO: Authenticating with Zendure ...
2024-07-31 10:11:33,965:INFO: Getting device list ...
2024-07-31 10:11:34,458:INFO: []
2024-07-31 10:11:34,460:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "/opt/solarflow-statuspage/solarflow-statuspage/src/solarflow-status.py", line 295, in zendure_mqtt_background_task
    auth = get_auth()
           ^^^^^^^^^^
  File "/opt/solarflow-statuspage/solarflow-statuspage/src/solarflow-status.py", line 288, in get_auth
    log.info(f'Zendure Auth: {auth}')
                              ^^^^
NameError: name 'auth' is not defined
```

**Comment by z-master42** [comment]
I am travelling with 0.19 and a Hub 1200 on the global and it works for me. What kind of hub are you using? What does the config or the environment variables look like?

**Comment by mrostock** [comment]
I'm using a Solarflow Hub 2000.
Here are my environment variables:
```
export ZEN_USER=<email adress>
export ZEN_PASSWD=<password>
export MQTT_HOST=<ip adress of lokal mqtt>
export MQTT_PORT=1883
export PROD_NAME="SolarFlow Hub 2000"
```

**Comment by z-master42** [comment]
What happens if you use "SolarFlow2.0" as PROD_NAME?

**Comment by mrostock** [comment]
Nothing has changed :-( Sorry!

**Comment by mrostock** [comment]
So, I found the issue:
My Zendure device is obviously on eu region ;-)
But the issue was that I tried to configure eu region by setting an environment variable:
`export ZEN_API=https://app.zendure.tech/eu`

But this environment variable has no effect due to the following line of code:
```
ZEN_API = config.get('zendure', 'zen_api', fallback='https://app.zendure.tech/v2') or os.environ.get('ZEN_API','https://app.zendure.tech/v2')
```

It reads the variable zen_api in configuration file `config.ini` and if variable is not set it will take fallback. The default `config.ini`is set to global region as well ;-)
I guess the environment variable will never be used.

Same with environment variable `ZEN_MQTT`

To fix this for me I had to set correct eu settings in config.ini.

So in docker environment it not possible to set eu region with environment variables. You must mount and change config.ini.

**Comment by z-master42** [comment]
Would it work if there is no config.ini at all?

This is not the only variable with a "either config.ini or environment variable".

**Comment by mrostock** [comment]
What if you define a config.ini as a skeleton which has no settings defined. All settings in config.ini are unset like this:
```
zen_mqtt = 
```

To define a default just specify the default only when getting it from environment variable, like this:
```
ZEN_API = config.get('zendure', 'zen_api') or os.environ.get('ZEN_API','https://app.zendure.tech/v2')
```
