### ISSUE TITLE
Authentication failed - since last update

### ISSUE THREAD

**Issue by AzraelsDisk** [reinhard-brandstaedter/solarflow-statuspage#50]
Watchdog updated today to :last version - since this update I got the following error
Running it on --online mode

Not sure if it is a problem of Zendure MQTT? 

2024-06-18` 20:33:47,860:INFO: Authenticating with Zendure ...
2024-06-18 20:33:48,922:ERROR: Authentication failed!
2024-06-18 20:33:48,927:ERROR: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>OBJECT</ResourceType><RequestId>SYAQ6VTNBZ9RXTY5</RequestId><HostId>k0UAFKEhWaF62XS07bQw01YRJSEkMNWIpNQTERTPScRjjEwaqfVMc938NRmfxOxbJQrF6qqRIlg=</HostId></Error>
2024-06-18 20:33:48,927:INFO: Getting device list ...
2024-06-18 20:33:49,733:ERROR: Fetching device list failed!
2024-06-18 20:33:49,737:ERROR: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>OBJECT</ResourceType><RequestId>WTE5VJHTJ9PJ0BXC</RequestId><HostId>a0Kfsh7bbiOOiRHLKMpH3dhhESVSFZzNBM7Cj53xNZdGwGBdqGYZZesAI3Q3RdLivfTuhTLUAiM=</HostId></Error>
2024-06-18 20:33:49,737:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "//solarflow-status.py", line 311, in zendure_mqtt_background_task
    auth = get_auth()
  File "//solarflow-status.py", line 298, in get_auth
    devices = api.get_device_ids()
  File "/zenapi/ZendureAPI.py", line 102, in get_device_ids
    for dev in devices:
TypeError: 'NoneType' object is not iterable

**Comment by z-master42** [comment]
Are you on the EU or the global server?

**Comment by reinhard-brandstaedter** [comment]
Interesting....nothing has changed in regards to the ZendureAPI.

**Comment by reinhard-brandstaedter** [comment]
Oh well [this change](https://github.com/reinhard-brandstaedter/solarflow-statuspage/commit/e5cc49062fdab3f0c82bffe9d5cc6951a5b5b5ed) indeed has now been built into the image.
So that change seems to break something.

**Comment by AzraelsDisk** [comment]
GlobalAm 18.06.2024 um 22:36 schrieb z-master42 ***@***.***>:﻿
Are you on the EU or the global server?

**Comment by AzraelsDisk** [comment]
I have redeployed version 0.19 and its working proper - was there a change in the configfile?

**Comment by reinhard-brandstaedter** [comment]
I believe @jvinkovic 's cjange regarding the EU API broke things. Has the EU/Global API really the same endpoint "v2" now?

**Comment by z-master42** [comment]
No, they are still v2 and eu. His approach was to remove the SF_API_VERSION and specify the entire server via ZEN_API. However, something still doesn't seem to fit, or there seem to be unused components in the code.

**Comment by AzraelsDisk** [comment]
can I do anything to support you, do you need additional logfiles?
