### ISSUE TITLE
the new master doesn't work on (my) hub2000 , the old dev worked!

### ISSUE THREAD

**Issue by joe63** [reinhard-brandstaedter/solarflow-statuspage#51]
hi,
I updated from :dev(worked)  to master. Now I get this Keyerror. Container run's but there is no connection to port 5000.

I get this message n the log-file.

2024-06-25 13:29:14,767:ERROR: No configuration file (config.ini) found in execution directory! Using environment variables.
2024-06-25 13:29:14,806:INFO: Connectiong local MQTT: 192.168.1.144:1883
2024-06-25 13:29:14,806:INFO: Connecting to MQTT with: solarflow-statuspage-86
2024-06-25 13:29:14,807:INFO: Subscribing to topics...
Traceback (most recent call last):
  File "//solarflow-status.py", line 419, in <module>
    setup()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in _call_
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "//solarflow-status.py", line 404, in setup
    local_mqtt_background_task()
  File "//solarflow-status.py", line 338, in local_mqtt_background_task
    local_subscribe(client)
  File "//solarflow-status.py", line 274, in local_subscribe
    report_topic = f'/{device_details["productKey"]}/+/properties/report'
KeyError: 'productKey'

**Comment by joe63** [comment]
the last :dev works

thank you!!

**Comment by joe63** [comment]
Hi, 
I have tried to step through the code of the solarflow-status:master to see where the key productKey in the device_details-dictionary should be inserted. I use it offline , so the  **get_auth()**  would not be used.

![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/6555368/b60b8e48-1fce-4a90-ba58-986c7e3c4826)


the section where the key is added to the dictionary **(2)** is used/executed later then the value is needed **(1)**


![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/6555368/37965e83-9500-41b2-b948-e28a8e65b10d)

when I insert the productkey and the deviceKey hardcoded in then setup-offline-section it works.
![image](https://github.com/reinhard-brandstaedter/solarflow-statuspage/assets/6555368/5e39f8fd-ef23-401b-9cf2-b540ccd1a9e8)

my main-question is: is there nobody else with this setting? 
and the sub-question is: does solarflow-control need solarflow-status? I think not it's only for visualizing?! when using homeassistant or any other mqtt-viewing-tool ist not needed and therefore the problem is at the time rarely to see.

**Comment by reinhard-brandstaedter** [comment]
master has not merged from dev, yet. The fix is only in dev at the moment.

Statuspage is not needed for sf-control, it is only a helper visualization/mobile app replacement.

The more common setup is sf-control, homeassistant and/or mqtt to timeseries database and visualization with e.g grafana.
