### ISSUE TITLE
NameError: name 'auth' is not defined

### ISSUE THREAD

**Issue by andig** [reinhard-brandstaedter/solarflow-statuspage#57]
Using .env file I'm unable to connect:

```
2024-11-04 07:40:31,116:ERROR: No configuration file (config.ini) found in execution directory! Using environment variables.
2024-11-04 07:40:31,130:INFO: Authenticating with Zendure ...
2024-11-04 07:40:32,082:INFO: Getting device list ...
2024-11-04 07:40:32,535:INFO: []
2024-11-04 07:40:32,535:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "//solarflow-status.py", line 305, in zendure_mqtt_background_task
    auth = get_auth()
  File "//solarflow-status.py", line 298, in get_auth
    log.info(f'Zendure Auth: {auth}')
NameError: name 'auth' is not defined
```

This is using a Hyper 2000.

**Comment by andig** [comment]
This might be the root cause:

```
2024-11-04 07:48:16,291:INFO: Getting device list ...
2024-11-04 07:48:16,738:DEBUG: https://app.zendure.tech:443 "POST /v2/productModule/device/queryDeviceListByConsumerId HTTP/11" 200 None
2024-11-04 07:48:16,739:INFO: []
```

**Comment by gintonic26** [comment]
Same problem here on my unraid server running the docker. 

> 2025-02-04 11:44:46,671:ERROR: No configuration file (config.ini) found in execution directory! Using environment variables.
2025-02-04 11:44:46,709:INFO: Authenticating with Zendure ...
2025-02-04 11:44:47,570:INFO: Getting device list ...
2025-02-04 11:44:47,844:INFO: []
2025-02-04 11:44:47,844:ERROR: Connecting to Zendure's MQTT broker failed!
Traceback (most recent call last):
  File "//solarflow-status.py", line 311, in zendure_mqtt_background_task
    auth = get_auth()
  File "//solarflow-status.py", line 304, in get_auth
    log.info(f'Zendure Auth: {auth}')
NameError: name 'auth' is not defined

**Comment by pascalbourges** [comment]
hi, have you resolved this issue ? i have the same.

**Comment by Arpris** [comment]
Hi,
Same problem here, @reinhard-brandstaedter could you help please ?
Thanks in advance
Arno

**Comment by jgrieger** [comment]
I had the same issue, running the Docker container. Root cause was that the code does not take the MQTT server that is delivered with the auth request (for EU, it's `"iotUrl": "mqtteu.zen-iot.com"` in the response). One could change the MQTT server manually editing the `config.ini`, but looking at e.g. the output of @gintonic26, this file is probably missing in the container image.

**Comment by dekrareha** [comment]
I have the same issue, can anyone please tell me where to place the config.ini? What is the "execution directory" Thank you in advance.
